services:

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  postgres-generator:
    image: postgres:16
    environment:
      POSTGRES_DB: generator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"

  postgres-registry:
    image: postgres:16
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"

  generator-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=generator-service
    ports:
      - "8080:8888"
    environment:
      - SERVER_PORT=8888
    depends_on:
      - kafka
      - postgres-generator

  registry-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=registry-service
    ports:
      - "8081:8889"
    environment:
      - SERVER_PORT=8889
    depends_on:
      - kafka
      - postgres-registry