spring:
  application:
    name: generator-service

  datasource:
    url: jdbc:postgresql://postgres-generator:5432/generator
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: generator-service
      auto-offset-reset: earliest
    topics:
      events-created: events.created
      events-confirmed: events.confirmed

  server:
    port: 8888
    name: generator-service